[project]
name = "2703-yamashita-bashelor-thesis"
version = "0.1.0"
description = "HHモデル・マルチコンパートメントモデルの微分方程式をRNNで置き換える卒業研究"
readme = "README.md"
authors = [
    { name = "yoheiyamahita-svg", email = "yoheiyamashita0821@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "efel>=5.7.34",
    "matplotlib>=3.10.9",
    "numpy>=2.2.6",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
