"""不規則変化表（変化形 → 原形）。"""

_VERBS = {
    "be": "am is are was were been being",
    "have": "has had having",
    "do": "does did done doing",
    "go": "goes went gone going",
    "run": "ran running",
    "take": "took taken taking",
    "make": "made making",
    "give": "gave given giving",
    "find": "found finding",
    "show": "showed shown",
    "know": "knew known",
    "see": "saw seen seeing",
    "write": "wrote written writing",
    "begin": "began begun beginning",
    "choose": "chose chosen choosing",
    "grow": "grew grown",
    "lead": "led",
    "hold": "held",
    "keep": "kept",
    "leave": "left",
    "lose": "lost",
    "mean": "meant",
    "set": "setting",
    "spend": "spent",
    "stand": "stood",
    "think": "thought",
    "understand": "understood",
    "bring": "brought",
    "buy": "bought",
    "build": "built",
    "come": "came",
    "draw": "drew drawn",
    "drive": "drove driven",
    "fall": "fell fallen",
    "feel": "felt",
    "get": "got gotten getting",
    "lay": "laid",
    "lie": "lay lain lying",
    "say": "said",
    "seek": "sought",
    "send": "sent",
    "shake": "shook shaken",
    "speak": "spoke spoken",
    "teach": "taught",
    "tell": "told",
    "throw": "threw thrown",
    "arise": "arose arisen",
    "bear": "bore borne",
    "bind": "bound",
    "break": "broke broken",
    "catch": "caught",
    "deal": "dealt",
    "forget": "forgot forgotten",
    "freeze": "froze frozen",
    "hide": "hid hidden",
    "learn": "learnt",
    "ride": "rode ridden",
    "rise": "rose risen",
    "sell": "sold",
    "shoot": "shot",
    "sit": "sat",
    "sleep": "slept",
    "strike": "struck",
    "swim": "swam swum",
    "wear": "wore worn",
    "win": "won",
    "undergo": "underwent undergone",
    "overcome": "overcame",
    "withdraw": "withdrew withdrawn",
}

_NOUNS = {
    "datum": "data",
    "analysis": "analyses",
    "hypothesis": "hypotheses",
    "thesis": "theses",
    "basis": "bases",
    "synthesis": "syntheses",
    "parenthesis": "parentheses",
    "criterion": "criteria",
    "phenomenon": "phenomena",
    "matrix": "matrices",
    "index": "indices",
    "vertex": "vertices",
    "appendix": "appendices",
    "stimulus": "stimuli",
    "nucleus": "nuclei",
    "radius": "radii",
    "locus": "loci",
    "spectrum": "spectra",
    "maximum": "maxima",
    "minimum": "minima",
    "medium": "media",
    "optimum": "optima",
    "quantum": "quanta",
    "formula": "formulae",
    "child": "children",
    "man": "men",
    "woman": "women",
    "mouse": "mice",
    "foot": "feet",
    "tooth": "teeth",
    "leaf": "leaves",
    "half": "halves",
    "life": "lives",
}

IRREGULAR: dict[str, str] = {}
for _base, _forms in {**_VERBS, **_NOUNS}.items():
    for _form in _forms.split():
        IRREGULAR.setdefault(_form, _base)
